/**
 * Stage 3 of county outlet discovery: write the registry.
 *
 * Reads the probe results and emits src/county-discovered-sources.ts, kept
 * separate from the hand-curated list in source-registry.ts so provenance stays
 * obvious — that list is described as reviewed outlets, and these are not
 * reviewed, they are observed.
 *
 * Every discovered source is emitted with trustedForCountyTier: false. Its feed
 * is fetched for the counties it was seen covering, which is where the extra
 * volume comes from, but its stories still have to name the county or one of
 * its towns to appear there.
 *
 * That restraint is deliberate. Trusting a source outright, the way the
 * reviewed Mena Star is trusted for Polk County, means every story it publishes
 * lands on that county's desk — correct for an outlet that covers one county,
 * ruinous for one that covers twenty. Counting how many counties a host was
 * observed in separates those cases well enough to sort a review queue, but not
 * well enough to grant trust automatically: on the Texas run that heuristic
 * called The Center Square, Courthouse News and Markets Insider county-native,
 * because they had each matched only a county or two. So the script writes a
 * review report instead, and promoting an outlet stays a human decision.
 *
 *   npm run emit:sources
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { EXCLUDED_PUBLISHER_HOSTS } from "./shared.js";
import type { ProbedHost } from "./shared.js";

const DEFAULT_OUTPUT = path.resolve("scripts/discover-sources/.out");
const REGISTRY_PATH = new URL("../../src/county-discovered-sources.ts", import.meta.url);

/** Counties an entry is written for, strongest coverage first. */
const MAX_COUNTIES_PER_SOURCE = 40;

/** Feeds kept per host. Beyond this they mostly repeat each other. */
const MAX_FEEDS_PER_SOURCE = 2;

/** Seen in at most this many counties: worth a look as a county-native outlet. */
const REVIEW_COUNTY_CEILING = 2;

async function main() {
  const outputDir = parseOutputDir(process.argv.slice(2));
  const probed = JSON.parse(await readFile(path.join(outputDir, "probed.json"), "utf8")) as ProbedHost[];

  const usable = probed.filter(
    (host) =>
      host.status === "ok" && host.feeds.length && host.counties.length && !EXCLUDED_PUBLISHER_HOSTS.has(host.host),
  );

  const sources = usable
    .flatMap((host) => {
      const name = cleanPublisherName(host.publisher, host.host);
      const counties = host.counties.slice(0, MAX_COUNTIES_PER_SOURCE);
      return host.feeds.slice(0, MAX_FEEDS_PER_SOURCE).map((feed, index) => ({
        name: index ? `${name} (${index + 1})` : name,
        // Probed before hrefs were entity-decoded, so old results still carry
        // "&amp;" in query strings. Harmless to re-apply.
        url: decodeHtmlEntities(feed.url),
        mediaType: "article" as const,
        itemSource: name,
        counties,
        trustedForCountyTier: false,
      }));
    })
    .sort((left, right) => left.name.localeCompare(right.name));

  const generated =
    `// Generated by: npm run discover:sources && npm run probe:sources && npm run emit:sources\n` +
    `// Do not edit by hand. Outlets promoted to trusted belong in the reviewed\n` +
    `// countyNativeSources list in source-registry.ts.\n` +
    `//\n` +
    `// Local and regional outlets observed writing about specific counties, each\n` +
    `// with a feed that parses and carries recent items. Their feeds are fetched\n` +
    `// for the counties listed, which is the point — it is where the additional\n` +
    `// county coverage comes from — but trustedForCountyTier is false throughout,\n` +
    `// so every story still has to name the county or one of its towns. Without\n` +
    `// that, one regional newsroom would fill twenty county desks with the same\n` +
    `// regional wire.\n` +
    `import type { CountyNativeSource, DirectSource } from "./source-registry.js";\n\n` +
    `// Reserved for outlets promoted after review; discovery never fills this.\n` +
    `export const discoveredCountyNativeSources: CountyNativeSource[] = [];\n\n` +
    `export const discoveredRegionalSources: DirectSource[] = ${JSON.stringify(sources, null, 2)};\n`;

  await writeFile(REGISTRY_PATH, generated, "utf8");

  const reviewPath = path.join(outputDir, "native-candidates.md");
  await writeFile(reviewPath, buildReviewReport(usable), "utf8");

  const counties = new Set(usable.flatMap((host) => host.counties));
  console.log(
    `Wrote ${sources.length} feeds from ${usable.length} outlets covering ${counties.size} counties.\n` +
      `Review candidates for trusted status: ${reviewPath}`,
  );
}

/**
 * Outlets that look county-native, for a human to promote. Ordered by how much
 * county coverage they were seen producing.
 */
function buildReviewReport(hosts: ProbedHost[]) {
  const candidates = hosts
    .filter((host) => host.counties.length <= REVIEW_COUNTY_CEILING)
    .sort((left, right) => left.counties.length - right.counties.length || left.host.localeCompare(right.host));

  const lines = [
    "# County-native candidates",
    "",
    "Outlets seen covering only one or two counties, each with a working feed.",
    "These are the ones plausibly worth trusting as county-local, the way the",
    "Mena Star is trusted for Polk County — meaning every story they publish",
    "would appear on that county's desk without needing to name it.",
    "",
    "Check that the outlet really is based in, and writes about, that county",
    "before promoting it into `countyNativeSources` in `src/source-registry.ts`.",
    "Statewide wires and trade press reach this list when they happen to have",
    "matched only a county or two.",
    "",
    "| Outlet | Host | Counties | Feed |",
    "| --- | --- | --- | --- |",
  ];

  for (const host of candidates) {
    lines.push(
      `| ${cleanPublisherName(host.publisher, host.host)} | ${host.host} | ${host.counties.join(", ")} | ${decodeHtmlEntities(host.feeds[0]?.url ?? "")} |`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/** Feed hrefs come out of HTML, so their entities are still encoded. */
function decodeHtmlEntities(value: string) {
  return value
    .replace(/&amp;/gi, "&")
    .replace(/&#38;/g, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">");
}

/** Prefers the masthead the feeds reported over a bare hostname. */
function cleanPublisherName(publisher: string, host: string) {
  const trimmed = publisher.trim();
  if (!trimmed || trimmed.toLowerCase() === host) {
    return host
      .replace(/\.(com|org|net|tv|news|us)$/i, "")
      .replace(/[.-]/g, " ")
      .replace(/\b\w/g, (character) => character.toUpperCase());
  }
  return trimmed.replace(/\s+on\s+MSN$/i, "").trim();
}

function parseOutputDir(argv: string[]) {
  const index = argv.indexOf("--output");
  return index >= 0 && argv[index + 1] ? path.resolve(argv[index + 1]) : DEFAULT_OUTPUT;
}

await main();
