import type { CountyAtlasDomain, CountyAtlasDomainInfo, CountyAtlasSource } from "./types.js";

export const atlasSources = {
  "census-acs": {
    id: "census-acs",
    name: "American Community Survey 5-Year Estimates",
    agency: "U.S. Census Bureau",
    url: "https://www.census.gov/programs-surveys/acs",
    cadence: "Annual",
    methodology: "Survey estimates include margins of error and should not be treated as exact counts.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  "census-popest": {
    id: "census-popest",
    name: "Population Estimates Program",
    agency: "U.S. Census Bureau",
    url: "https://www.census.gov/programs-surveys/popest.html",
    cadence: "Annual",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  "census-saipe": {
    id: "census-saipe",
    name: "Small Area Income and Poverty Estimates",
    agency: "U.S. Census Bureau",
    url: "https://www.census.gov/programs-surveys/saipe.html",
    cadence: "Annual",
    methodology: "Model-based county income and poverty estimates.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  "census-cbp": {
    id: "census-cbp",
    name: "County Business Patterns",
    agency: "U.S. Census Bureau",
    url: "https://www.census.gov/programs-surveys/cbp.html",
    cadence: "Annual",
    methodology: "Employer businesses; some values are suppressed to protect confidentiality.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  "bls-laus": {
    id: "bls-laus",
    name: "Local Area Unemployment Statistics",
    agency: "U.S. Bureau of Labor Statistics",
    url: "https://www.bls.gov/lau/",
    cadence: "Monthly and annual",
    methodology: "Model-based labor-force estimates that may be revised.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  "bls-qcew": {
    id: "bls-qcew",
    name: "Quarterly Census of Employment and Wages",
    agency: "U.S. Bureau of Labor Statistics",
    url: "https://www.bls.gov/cew/",
    cadence: "Quarterly",
    methodology: "Covers more than 95% of U.S. jobs; confidential values may be suppressed.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  bea: {
    id: "bea",
    name: "Regional Economic Accounts",
    agency: "U.S. Bureau of Economic Analysis",
    url: "https://www.bea.gov/data/by-place-county-metro-local",
    cadence: "Annual",
    methodology: "Some small counties and independent cities are combined in BEA geographies.",
    licenseNote: "U.S. government public data; BEA attribution and non-endorsement notice apply.",
  },
  fred: {
    id: "fred",
    name: "Federal Reserve Economic Data",
    agency: "Federal Reserve Bank of St. Louis",
    url: "https://fred.stlouisfed.org/",
    cadence: "Varies by series",
    methodology: "Series are republished from originating agencies; source-specific terms may apply.",
  },
  "cdc-places": {
    id: "cdc-places",
    name: "PLACES",
    agency: "Centers for Disease Control and Prevention",
    url: "https://www.cdc.gov/places/",
    cadence: "Annual",
    methodology: "County values are modeled estimates, not direct counts.",
    licenseNote: "U.S. government public data; citation requested.",
  },
  nces: {
    id: "nces",
    name: "Common Core of Data and EDGE",
    agency: "National Center for Education Statistics",
    url: "https://nces.ed.gov/ccd/",
    cadence: "Annual",
    methodology: "School districts can cross county boundaries; allocation method is retained with each measure.",
    licenseNote: "Public-use U.S. government data; attribution requested.",
  },
  "usda-nass": {
    id: "usda-nass",
    name: "Census of Agriculture and Quick Stats",
    agency: "U.S. Department of Agriculture",
    url: "https://www.nass.usda.gov/AgCensus/",
    cadence: "Five-year census and periodic estimates",
    methodology: "Disclosure-suppressed values are unavailable and are never represented as zero.",
    licenseNote: "U.S. government public data; attribution and non-endorsement notice apply.",
  },
  "fbi-cde": {
    id: "fbi-cde",
    name: "Crime Data Explorer",
    agency: "Federal Bureau of Investigation",
    url: "https://cde.ucr.cjis.gov/",
    cadence: "Monthly and annual",
    methodology: "Agency reporting is voluntary; coverage and jurisdiction overlap vary by county.",
    licenseNote: "U.S. government open data; attribution requested.",
  },
  "nhtsa-fars": {
    id: "nhtsa-fars",
    name: "Fatality Analysis Reporting System",
    agency: "National Highway Traffic Safety Administration",
    url: "https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars",
    cadence: "Annual",
    methodology: "A census of motor-vehicle crashes involving a fatality; county is crash-location geography, not a measure of all crime or public-safety incidents.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  medsl: {
    id: "medsl",
    name: "County Presidential Election Returns",
    agency: "MIT Election Data and Science Lab",
    url: "https://electionlab.mit.edu/data",
    cadence: "After federal elections",
    methodology: "Normalized from official state results; Alaska and non-county reporting geographies require caveats.",
    licenseNote: "CC0 dataset; retain provenance to certified state results.",
  },
  "census-govs": {
    id: "census-govs",
    name: "Census of Governments",
    agency: "U.S. Census Bureau",
    url: "https://www.census.gov/programs-surveys/cog.html",
    cadence: "Five-year census with annual surveys",
    methodology: "Government units and service areas may overlap county boundaries.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  usaspending: {
    id: "usaspending",
    name: "USAspending",
    agency: "U.S. Department of the Treasury",
    url: "https://www.usaspending.gov/",
    cadence: "Nightly pipeline; agency submissions vary",
    methodology: "Place of performance and recipient location are distinct measures.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
  fema: {
    id: "fema",
    name: "OpenFEMA and National Risk Index",
    agency: "Federal Emergency Management Agency",
    url: "https://www.fema.gov/about/openfema/data-sets",
    cadence: "Continuous and release-based",
    methodology: "Risk scores are modeled; statewide and tribal declarations may not map to counties.",
    licenseNote: "OpenFEMA citation and non-endorsement notice apply.",
  },
  epa: {
    id: "epa",
    name: "Envirofacts and AirData",
    agency: "U.S. Environmental Protection Agency",
    url: "https://www.epa.gov/enviro",
    cadence: "Varies by program",
    methodology: "Facilities and monitors do not provide uniform population coverage.",
    licenseNote: "U.S. government public data; source citation requested.",
  },
  fcc: {
    id: "fcc",
    name: "National Broadband Map",
    agency: "Federal Communications Commission",
    url: "https://broadbandmap.fcc.gov/data-download",
    cadence: "Twice yearly",
    methodology: "Provider-reported availability is not the same as adoption or measured speed.",
    licenseNote: "Only public county summaries are redistributed; restricted Fabric data is excluded.",
  },
  hud: {
    id: "hud",
    name: "HUD USER Datasets",
    agency: "U.S. Department of Housing and Urban Development",
    url: "https://www.huduser.gov/portal/pdrdatas_landing.html",
    cadence: "Annual and quarterly",
    methodology: "Some HUD geographies are metropolitan or program areas rather than counties.",
    licenseNote: "Attribution and non-endorsement notice apply.",
  },
  fhwa: {
    id: "fhwa",
    name: "National Bridge Inventory",
    agency: "Federal Highway Administration",
    url: "https://www.fhwa.dot.gov/bridge/nbi.cfm",
    cadence: "Annual",
    methodology: "Inspection dates vary; condition ratings describe structures, not network-wide service quality.",
    licenseNote: "U.S. government public data; attribution requested.",
  },
} satisfies Record<string, CountyAtlasSource>;

export const atlasDomains: Record<CountyAtlasDomain, CountyAtlasDomainInfo> = {
  demographics: domain(
    "demographics",
    "Demographics",
    "People",
    "Population, age, households, race and ethnicity, migration, disability, veterans, and language.",
    ["census-acs", "census-popest"],
    ["population", "median-age", "households", "veterans"],
  ),
  economy: domain(
    "economy",
    "Economy & Income",
    "Economy",
    "Income, poverty, output, labor force, unemployment, and economic growth.",
    ["census-acs", "census-saipe", "bls-laus", "bea", "fred"],
    ["median-household-income", "per-capita-income", "unemployment-rate", "poverty-rate", "gini-index"],
  ),
  housing: domain(
    "housing",
    "Housing",
    "Housing",
    "Home values, rent, costs, occupancy, vacancy, tenure, and housing supply.",
    ["census-acs", "hud"],
    ["median-home-value", "median-gross-rent", "homeownership-rate", "vacancy-rate", "rent-cost-burden-rate", "median-year-built"],
  ),
  "jobs-business": domain(
    "jobs-business",
    "Jobs & Business",
    "Jobs",
    "Employment, wages, establishments, industries, commuting, and business activity.",
    ["census-acs", "bls-qcew", "census-cbp"],
    ["employment", "labor-force-participation", "mean-commute"],
  ),
  education: domain(
    "education",
    "Education",
    "Schools",
    "Educational attainment, enrollment, public schools, students, and district context.",
    ["census-acs", "nces"],
    ["high-school-graduate-rate", "bachelors-rate", "school-enrollment"],
  ),
  health: domain(
    "health",
    "Health",
    "Health",
    "Health coverage, disability, chronic conditions, preventive care, and modeled outcomes.",
    ["census-acs", "cdc-places"],
    ["disability-rate", "uninsured-rate"],
  ),
  "civic-elections": domain(
    "civic-elections",
    "Civic Life & Elections",
    "Civic",
    "Election results, turnout, registration context, and civic participation.",
    ["census-acs", "medsl"],
    ["voting-age-population"],
  ),
  "public-safety": domain(
    "public-safety",
    "Public Safety",
    "Safety",
    "Fatal traffic crashes and deaths, with future crime data published only when county reporting coverage is defensible.",
    ["nhtsa-fars", "fbi-cde"],
    ["traffic-fatal-crashes", "traffic-deaths"],
  ),
  agriculture: domain(
    "agriculture",
    "Agriculture",
    "Farms",
    "Farms, land, sales, producers, livestock, crops, and disclosure-aware agricultural totals.",
    ["census-acs", "usda-nass"],
    ["agriculture-mining-employment"],
  ),
  "environment-disasters": domain(
    "environment-disasters",
    "Environment & Disasters",
    "Environment",
    "Natural-hazard risk, disaster declarations, regulated facilities, and air-monitor context.",
    ["fema", "epa"],
    ["disaster-declarations-5y", "major-disaster-declarations-5y", "latest-disaster-declaration"],
  ),
  "government-finance": domain(
    "government-finance",
    "Government & Public Finance",
    "Government",
    "Government units, public employment, revenue, spending, and federal awards.",
    ["census-acs", "census-govs", "usaspending"],
    ["median-real-estate-taxes"],
  ),
  infrastructure: domain(
    "infrastructure",
    "Infrastructure & Connectivity",
    "Infrastructure",
    "Broadband availability, bridges, transportation assets, utilities, and critical facilities.",
    ["census-acs", "fcc", "fhwa"],
    ["internet-subscription-rate", "no-vehicle-households-rate", "work-from-home-rate", "drive-alone-commuter-rate"],
  ),
};

export function getAtlasDomain(value: string): CountyAtlasDomainInfo | undefined {
  return atlasDomains[value as CountyAtlasDomain];
}

export function getAtlasSources(ids: string[]): CountyAtlasSource[] {
  return ids.flatMap((id) => {
    const source = atlasSources[id as keyof typeof atlasSources];
    return source ? [source] : [];
  });
}

function domain(
  slug: CountyAtlasDomain,
  label: string,
  shortLabel: string,
  description: string,
  sourceIds: string[],
  metricKeys: string[],
): CountyAtlasDomainInfo {
  return { slug, label, shortLabel, description, sourceIds, metricKeys };
}
