// Generated by: npm run discover:sources && npm run probe:sources && npm run emit:sources
// Do not edit by hand. Outlets promoted to trusted belong in the reviewed
// countyNativeSources list in source-registry.ts.
//
// Local and regional outlets observed writing about specific counties, each
// with a feed that parses and carries recent items. Their feeds are fetched
// for the counties listed, which is the point — it is where the additional
// county coverage comes from — but trustedForCountyTier is false throughout,
// so every story still has to name the county or one of its towns. Without
// that, one regional newsroom would fill twenty county desks with the same
// regional wire.
import type { CountyNativeSource, DirectSource } from "./source-registry.js";

// Reserved for outlets promoted after review; discovery never fills this.
export const discoveredCountyNativeSources: CountyNativeSource[] = [];

export const discoveredRegionalSources: DirectSource[] = [
  {
    "name": "101.5 KNUE Country Radio",
    "url": "https://knue.com/feed/",
    "mediaType": "article",
    "itemSource": "101.5 KNUE Country Radio",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "101.5 KNUE Country Radio (2)",
    "url": "https://knue.com/rss",
    "mediaType": "article",
    "itemSource": "101.5 KNUE Country Radio",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "12 NEWS",
    "url": "https://www.12newsnow.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "12 NEWS",
    "counties": [
      "texas/jasper",
      "texas/orange",
      "texas/tyler",
      "texas/jefferson",
      "texas/newton",
      "texas/palo-pinto",
      "texas/blanco",
      "texas/brooks",
      "texas/sabine",
      "texas/hardin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "13abc",
    "url": "https://13abc.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "13abc",
    "counties": [
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "25 News KXXV",
    "url": "https://www.kxxv.com/index.rss",
    "mediaType": "article",
    "itemSource": "25 News KXXV",
    "counties": [
      "texas/hamilton",
      "texas/mclennan"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ABC10",
    "url": "https://www.abc10.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "ABC10",
    "counties": [
      "texas/trinity"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ABC13 Houston",
    "url": "https://abc13.com/feed/",
    "mediaType": "article",
    "itemSource": "ABC13 Houston",
    "counties": [
      "texas/matagorda",
      "texas/houston",
      "texas/fort-bend",
      "texas/leon",
      "texas/liberty",
      "texas/waller",
      "texas/jackson",
      "texas/harris",
      "texas/san-jacinto",
      "texas/henderson",
      "texas/kinney",
      "texas/tarrant",
      "texas/walker",
      "texas/brazoria",
      "texas/chambers",
      "texas/gregg",
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ABC13 Houston (2)",
    "url": "https://abc13.com/rss",
    "mediaType": "article",
    "itemSource": "ABC13 Houston",
    "counties": [
      "texas/matagorda",
      "texas/houston",
      "texas/fort-bend",
      "texas/leon",
      "texas/liberty",
      "texas/waller",
      "texas/jackson",
      "texas/harris",
      "texas/san-jacinto",
      "texas/henderson",
      "texas/kinney",
      "texas/tarrant",
      "texas/walker",
      "texas/brazoria",
      "texas/chambers",
      "texas/gregg",
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Action News Now",
    "url": "http://www.actionnewsnow.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Action News Now",
    "counties": [
      "texas/trinity"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "AgriLife Today",
    "url": "https://agrilifetoday.tamu.edu/feed/",
    "mediaType": "article",
    "itemSource": "AgriLife Today",
    "counties": [
      "texas/mason"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "AgriLife Today (2)",
    "url": "https://agrilifetoday.tamu.edu/rss",
    "mediaType": "article",
    "itemSource": "AgriLife Today",
    "counties": [
      "texas/mason"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Athens Review",
    "url": "http://www.athensreview.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Athens Review",
    "counties": [
      "texas/henderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Bluebonnet News",
    "url": "https://bluebonnetnews.com/feed/",
    "mediaType": "article",
    "itemSource": "Bluebonnet News",
    "counties": [
      "texas/liberty",
      "texas/live-oak"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Bluebonnet News (2)",
    "url": "https://bluebonnetnews.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "Bluebonnet News",
    "counties": [
      "texas/liberty",
      "texas/live-oak"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Cbs19",
    "url": "https://www.cbs19.tv/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Cbs19",
    "counties": [
      "texas/wood",
      "texas/angelina",
      "texas/harrison",
      "texas/anderson",
      "texas/rusk"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Click2Houston",
    "url": "https://click2houston.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "Click2Houston",
    "counties": [
      "texas/polk",
      "texas/galveston",
      "texas/liberty",
      "texas/austin",
      "texas/matagorda",
      "texas/san-jacinto",
      "texas/brazoria",
      "texas/midland",
      "texas/uvalde",
      "texas/harris",
      "texas/houston",
      "texas/chambers",
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Colorado Politics",
    "url": "https://www.coloradopolitics.com/feed/",
    "mediaType": "article",
    "itemSource": "Colorado Politics",
    "counties": [
      "texas/el-paso"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Colorado Politics (2)",
    "url": "https://coloradopolitics.com/feed/",
    "mediaType": "article",
    "itemSource": "Colorado Politics",
    "counties": [
      "texas/el-paso"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Community Impact",
    "url": "https://communityimpact.com/rss/",
    "mediaType": "article",
    "itemSource": "Community Impact",
    "counties": [
      "texas/williamson",
      "texas/collin",
      "texas/brazos",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Community Impact (2)",
    "url": "https://communityimpact.com/rss",
    "mediaType": "article",
    "itemSource": "Community Impact",
    "counties": [
      "texas/williamson",
      "texas/collin",
      "texas/brazos",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Crooks and Liars",
    "url": "https://crooksandliars.com/feeds/latest",
    "mediaType": "article",
    "itemSource": "Crooks and Liars",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Crooks and Liars (2)",
    "url": "http://feeds.crooksandliars.com/crooksandliars/YaCP",
    "mediaType": "article",
    "itemSource": "Crooks and Liars",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Cross Timbers Gazette",
    "url": "https://www.crosstimbersgazette.com/feed/",
    "mediaType": "article",
    "itemSource": "Cross Timbers Gazette",
    "counties": [
      "texas/denton"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Cross Timbers Gazette (2)",
    "url": "https://crosstimbersgazette.com/feed/",
    "mediaType": "article",
    "itemSource": "Cross Timbers Gazette",
    "counties": [
      "texas/denton"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Crossroads Today",
    "url": "http://www.crossroadstoday.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Crossroads Today",
    "counties": [
      "texas/jackson",
      "texas/calhoun",
      "texas/fort-bend",
      "texas/guadalupe",
      "texas/goliad"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Dailyyonder",
    "url": "https://dailyyonder.com/feed/",
    "mediaType": "article",
    "itemSource": "Dailyyonder",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Dailyyonder (2)",
    "url": "https://dailyyonder.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "Dailyyonder",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Denton Record-Chronicle",
    "url": "http://dentonrc.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Denton Record-Chronicle",
    "counties": [
      "texas/denton"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Eagle Pass Business Journal",
    "url": "https://epbusinessjournal.com/feed/",
    "mediaType": "article",
    "itemSource": "Eagle Pass Business Journal",
    "counties": [
      "texas/maverick"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Eagle Pass Business Journal (2)",
    "url": "https://epbusinessjournal.com/rss",
    "mediaType": "article",
    "itemSource": "Eagle Pass Business Journal",
    "counties": [
      "texas/maverick"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Electrek",
    "url": "https://electrek.co/feed/",
    "mediaType": "article",
    "itemSource": "Electrek",
    "counties": [
      "texas/swisher"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Electrek (2)",
    "url": "https://electrek.co/rss",
    "mediaType": "article",
    "itemSource": "Electrek",
    "counties": [
      "texas/swisher"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 26 Houston",
    "url": "https://www.fox26houston.com/rss.xml",
    "mediaType": "article",
    "itemSource": "FOX 26 Houston",
    "counties": [
      "texas/galveston"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 26 Houston (2)",
    "url": "https://www.fox26houston.com/rss/category/news",
    "mediaType": "article",
    "itemSource": "FOX 26 Houston",
    "counties": [
      "texas/galveston"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 4 News Dallas-Fort Worth",
    "url": "https://www.fox4news.com/rss.xml",
    "mediaType": "article",
    "itemSource": "FOX 4 News Dallas-Fort Worth",
    "counties": [
      "texas/van-zandt",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 4 News Dallas-Fort Worth (2)",
    "url": "https://www.fox4news.com/rss/category/news",
    "mediaType": "article",
    "itemSource": "FOX 4 News Dallas-Fort Worth",
    "counties": [
      "texas/van-zandt",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 7 Austin",
    "url": "https://www.fox7austin.com/rss.xml",
    "mediaType": "article",
    "itemSource": "FOX 7 Austin",
    "counties": [
      "texas/uvalde"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 7 Austin (2)",
    "url": "https://www.fox7austin.com/rss/category/news",
    "mediaType": "article",
    "itemSource": "FOX 7 Austin",
    "counties": [
      "texas/uvalde"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FreightWaves",
    "url": "https://freightwaves.com/feed/",
    "mediaType": "article",
    "itemSource": "FreightWaves",
    "counties": [
      "texas/hidalgo"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FreightWaves (2)",
    "url": "https://freightwaves.com/rss",
    "mediaType": "article",
    "itemSource": "FreightWaves",
    "counties": [
      "texas/hidalgo"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Government Technology",
    "url": "https://www.govtech.com/index.rss",
    "mediaType": "article",
    "itemSource": "Government Technology",
    "counties": [
      "texas/coryell",
      "texas/johnson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Houston Public Media",
    "url": "https://www.houstonpublicmedia.org/rsslatest.xml",
    "mediaType": "article",
    "itemSource": "Houston Public Media",
    "counties": [
      "texas/galveston",
      "texas/polk",
      "texas/houston",
      "texas/harris",
      "texas/mclennan",
      "texas/montgomery",
      "texas/waller"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Houston Public Media (2)",
    "url": "https://houstonpublicmedia.org/feed/",
    "mediaType": "article",
    "itemSource": "Houston Public Media",
    "counties": [
      "texas/galveston",
      "texas/polk",
      "texas/houston",
      "texas/harris",
      "texas/mclennan",
      "texas/montgomery",
      "texas/waller"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Independent Journal Review",
    "url": "https://ijr.com/feed/",
    "mediaType": "article",
    "itemSource": "Independent Journal Review",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Independent Journal Review (2)",
    "url": "https://ijr.com/feed.xml",
    "mediaType": "article",
    "itemSource": "Independent Journal Review",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Insurance Journal",
    "url": "https://insurancejournal.com/feed/",
    "mediaType": "article",
    "itemSource": "Insurance Journal",
    "counties": [
      "texas/gregg",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Insurance Journal (2)",
    "url": "https://insurancejournal.com/rss",
    "mediaType": "article",
    "itemSource": "Insurance Journal",
    "counties": [
      "texas/gregg",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KAGS",
    "url": "https://www.kagstv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KAGS",
    "counties": [
      "texas/brazos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KARE",
    "url": "https://www.kare11.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KARE",
    "counties": [
      "texas/washington"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KBTX News 3",
    "url": "https://kbtx.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KBTX News 3",
    "counties": [
      "texas/palo-pinto",
      "texas/leon",
      "texas/walker",
      "texas/lee",
      "texas/fayette",
      "texas/childress",
      "texas/madison",
      "texas/burleson",
      "texas/brazos",
      "texas/erath",
      "texas/robertson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KCBD",
    "url": "https://kcbd.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KCBD",
    "counties": [
      "texas/lubbock",
      "texas/hale",
      "texas/williamson",
      "texas/garza"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KCEN-TV",
    "url": "https://www.kcentv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KCEN-TV",
    "counties": [
      "texas/hamilton",
      "texas/lampasas",
      "texas/palo-pinto",
      "texas/brazos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KDRV NewsWatch 12",
    "url": "http://www.kdrv.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "KDRV NewsWatch 12",
    "counties": [
      "texas/trinity"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KHNL",
    "url": "https://hawaiinewsnow.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KHNL",
    "counties": [
      "texas/ward"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KHOU",
    "url": "https://www.khou.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KHOU",
    "counties": [
      "texas/galveston",
      "texas/houston",
      "texas/val-verde",
      "texas/montgomery",
      "texas/childress",
      "texas/waller",
      "texas/wharton",
      "texas/kendall",
      "texas/victoria",
      "texas/harris",
      "texas/kerr",
      "texas/nacogdoches",
      "texas/zavala",
      "texas/brazoria",
      "texas/liberty",
      "texas/real",
      "texas/bell",
      "texas/grimes",
      "texas/rockwall",
      "texas/polk",
      "texas/sabine",
      "texas/brazos",
      "texas/ector",
      "texas/tyler",
      "texas/chambers",
      "texas/fort-bend",
      "texas/san-jacinto",
      "texas/travis",
      "texas/wise"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KICKS 105",
    "url": "https://kicks105.com/feed/",
    "mediaType": "article",
    "itemSource": "KICKS 105",
    "counties": [
      "texas/san-augustine"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KICKS 105 (2)",
    "url": "https://kicks105.com/rss",
    "mediaType": "article",
    "itemSource": "KICKS 105",
    "counties": [
      "texas/san-augustine"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Kiii3 News",
    "url": "https://www.kiiitv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Kiii3 News",
    "counties": [
      "texas/aransas",
      "texas/mcmullen",
      "texas/live-oak",
      "texas/bee",
      "texas/goliad",
      "texas/jim-hogg",
      "texas/kleberg",
      "texas/brooks",
      "texas/nueces",
      "texas/burleson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Killeen Daily Herald",
    "url": "http://kdhnews.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Killeen Daily Herald",
    "counties": [
      "texas/bee",
      "texas/refugio",
      "texas/live-oak",
      "texas/goliad",
      "texas/washington",
      "texas/bell"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KLTV",
    "url": "https://kltv.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KLTV",
    "counties": [
      "texas/henderson",
      "texas/angelina",
      "texas/rusk",
      "texas/wood",
      "texas/cherokee",
      "texas/gregg",
      "texas/marion",
      "texas/smith",
      "texas/houston",
      "texas/anderson",
      "texas/franklin",
      "texas/harrison",
      "texas/hopkins",
      "texas/newton",
      "texas/rains",
      "texas/upshur"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Kristv",
    "url": "https://www.kristv.com/index.rss",
    "mediaType": "article",
    "itemSource": "Kristv",
    "counties": [
      "texas/refugio",
      "texas/live-oak",
      "texas/nueces",
      "texas/bee",
      "texas/kenedy",
      "texas/aransas",
      "texas/jim-wells",
      "texas/brooks",
      "texas/san-patricio",
      "texas/kleberg"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KSAT",
    "url": "https://ksat.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KSAT",
    "counties": [
      "texas/bandera",
      "texas/maverick",
      "texas/medina",
      "texas/frio",
      "texas/live-oak",
      "texas/gillespie",
      "texas/uvalde",
      "texas/wilson",
      "texas/edwards",
      "texas/karnes",
      "texas/kendall",
      "texas/la-salle",
      "texas/lavaca",
      "texas/fayette",
      "texas/kinney",
      "texas/guadalupe",
      "texas/comal",
      "texas/val-verde",
      "texas/blanco",
      "texas/brazoria",
      "texas/goliad",
      "texas/atascosa",
      "texas/hays",
      "texas/zavala",
      "texas/bexar",
      "texas/brooks",
      "texas/foard",
      "texas/howard",
      "texas/hunt",
      "texas/midland",
      "texas/bee",
      "texas/kimble"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KSLA",
    "url": "https://ksla.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KSLA",
    "counties": [
      "texas/marion",
      "texas/harrison",
      "texas/bowie",
      "texas/cass"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KTBS",
    "url": "http://www.ktbs.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "KTBS",
    "counties": [
      "texas/marion",
      "texas/bowie",
      "texas/panola",
      "texas/zavala"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KTEN",
    "url": "http://www.kten.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "KTEN",
    "counties": [
      "texas/grayson",
      "texas/fannin",
      "texas/cooke"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KTRE",
    "url": "https://ktre.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KTRE",
    "counties": [
      "texas/houston",
      "texas/angelina",
      "texas/tyler",
      "texas/nacogdoches",
      "texas/shelby",
      "texas/trinity"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVIA",
    "url": "https://kvia.com/feed/",
    "mediaType": "article",
    "itemSource": "KVIA",
    "counties": [
      "texas/culberson",
      "texas/hudspeth"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVIA (2)",
    "url": "https://kvia.com/rss",
    "mediaType": "article",
    "itemSource": "KVIA",
    "counties": [
      "texas/culberson",
      "texas/hudspeth"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVUE",
    "url": "https://www.kvue.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KVUE",
    "counties": [
      "texas/williamson",
      "texas/mason",
      "texas/fayette",
      "texas/gillespie",
      "texas/milam",
      "texas/bastrop",
      "texas/jim-hogg",
      "texas/travis",
      "texas/comal",
      "texas/henderson",
      "texas/lee",
      "texas/palo-pinto",
      "texas/wilbarger",
      "texas/bee",
      "texas/blanco",
      "texas/burnet",
      "texas/caldwell",
      "texas/hill",
      "texas/llano",
      "texas/orange",
      "texas/brazoria",
      "texas/kinney"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KWTX",
    "url": "https://kwtx.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KWTX",
    "counties": [
      "texas/mclennan",
      "texas/hill",
      "texas/coryell",
      "texas/falls",
      "texas/milam",
      "texas/angelina",
      "texas/childress",
      "texas/san-jacinto",
      "texas/limestone",
      "texas/guadalupe",
      "texas/bell",
      "texas/hamilton",
      "texas/leon",
      "texas/bosque",
      "texas/lampasas",
      "texas/tom-green"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KXAN Austin",
    "url": "https://www.kxan.com/feed/",
    "mediaType": "article",
    "itemSource": "KXAN Austin",
    "counties": [
      "texas/williamson",
      "texas/blanco",
      "texas/bastrop",
      "texas/mason",
      "texas/caldwell",
      "texas/fayette",
      "texas/gillespie",
      "texas/midland",
      "texas/starr",
      "texas/zavala",
      "texas/travis",
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KXAN Austin (2)",
    "url": "https://www.kxan.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "KXAN Austin",
    "counties": [
      "texas/williamson",
      "texas/blanco",
      "texas/bastrop",
      "texas/mason",
      "texas/caldwell",
      "texas/fayette",
      "texas/gillespie",
      "texas/midland",
      "texas/starr",
      "texas/zavala",
      "texas/travis",
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Law",
    "url": "https://law.com/news/feed/",
    "mediaType": "article",
    "itemSource": "Law",
    "counties": [
      "texas/guadalupe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Levelland & Hockley County News Press",
    "url": "https://levellandnews.net/rss.xml",
    "mediaType": "article",
    "itemSource": "Levelland & Hockley County News Press",
    "counties": [
      "texas/hockley"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Longview News-Journal",
    "url": "https://news-journal.com/feed/",
    "mediaType": "article",
    "itemSource": "Longview News-Journal",
    "counties": [
      "texas/franklin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Longview News-Journal (2)",
    "url": "https://news-journal.com/rss",
    "mediaType": "article",
    "itemSource": "Longview News-Journal",
    "counties": [
      "texas/franklin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Los Angeles Times",
    "url": "https://www.latimes.com/index.rss",
    "mediaType": "article",
    "itemSource": "Los Angeles Times",
    "counties": [
      "texas/hood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "MPR News",
    "url": "https://www.mprnews.org/feed/homepage",
    "mediaType": "article",
    "itemSource": "MPR News",
    "counties": [
      "texas/washington"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ms",
    "url": "https://www.ms.now/feed",
    "mediaType": "article",
    "itemSource": "ms",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ms (2)",
    "url": "https://ms.now/feed/",
    "mediaType": "article",
    "itemSource": "ms",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NBC DFW",
    "url": "https://www.nbcdfw.com/?rss=y",
    "mediaType": "article",
    "itemSource": "NBC DFW",
    "counties": [
      "texas/crockett",
      "texas/hopkins",
      "texas/denton",
      "texas/hunt",
      "texas/collin",
      "texas/fannin",
      "texas/kaufman"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NBC DFW (2)",
    "url": "https://nbcdfw.com/feed/",
    "mediaType": "article",
    "itemSource": "NBC DFW",
    "counties": [
      "texas/crockett",
      "texas/hopkins",
      "texas/denton",
      "texas/hunt",
      "texas/collin",
      "texas/fannin",
      "texas/kaufman"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "New York Post",
    "url": "https://nypost.com/feed/",
    "mediaType": "article",
    "itemSource": "New York Post",
    "counties": [
      "texas/maverick",
      "texas/webb",
      "texas/jefferson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "New York Post (2)",
    "url": "https://nypost.com/rss",
    "mediaType": "article",
    "itemSource": "New York Post",
    "counties": [
      "texas/maverick",
      "texas/webb",
      "texas/jefferson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "News Channel 6",
    "url": "https://newschannel6now.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "News Channel 6",
    "counties": [
      "texas/wichita"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "News4Jax",
    "url": "https://news4jax.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "News4Jax",
    "counties": [
      "texas/clay"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NewsChannel 10",
    "url": "https://newschannel10.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "NewsChannel 10",
    "counties": [
      "texas/wheeler",
      "texas/hutchinson",
      "texas/deaf-smith"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NewsWest 9",
    "url": "https://www.newswest9.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "NewsWest 9",
    "counties": [
      "texas/presidio",
      "texas/howard",
      "texas/winkler",
      "texas/midland",
      "texas/reeves",
      "texas/crane",
      "texas/andrews",
      "texas/ector",
      "texas/terrell",
      "texas/ward",
      "texas/pecos",
      "texas/brewster",
      "texas/scurry",
      "texas/upton",
      "texas/martin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "PolitiFact",
    "url": "https://politifact.com/feed/",
    "mediaType": "article",
    "itemSource": "PolitiFact",
    "counties": [
      "texas/gaines"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "PolitiFact (2)",
    "url": "https://politifact.com/rss",
    "mediaType": "article",
    "itemSource": "PolitiFact",
    "counties": [
      "texas/gaines"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Post and Courier",
    "url": "https://www.postandcourier.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Post and Courier",
    "counties": [
      "texas/falls"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "POWER Magazine",
    "url": "https://powermag.com/feed/",
    "mediaType": "article",
    "itemSource": "POWER Magazine",
    "counties": [
      "texas/haskell",
      "texas/runnels",
      "texas/calhoun",
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "POWER Magazine (2)",
    "url": "https://powermag.com/rss",
    "mediaType": "article",
    "itemSource": "POWER Magazine",
    "counties": [
      "texas/haskell",
      "texas/runnels",
      "texas/calhoun",
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ProPublica",
    "url": "https://www.propublica.org/feeds/propublica/main",
    "mediaType": "article",
    "itemSource": "ProPublica",
    "counties": [
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ProPublica (2)",
    "url": "https://propublica.org/feed/",
    "mediaType": "article",
    "itemSource": "ProPublica",
    "counties": [
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "REBusinessOnline",
    "url": "https://rebusinessonline.com/feed/",
    "mediaType": "article",
    "itemSource": "REBusinessOnline",
    "counties": [
      "texas/briscoe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "REBusinessOnline (2)",
    "url": "https://rebusinessonline.com/rss",
    "mediaType": "article",
    "itemSource": "REBusinessOnline",
    "counties": [
      "texas/briscoe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Royse City Herald-Banner",
    "url": "http://www.roysecityheraldbanner.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "Royse City Herald-Banner",
    "counties": [
      "texas/rockwall"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Current",
    "url": "https://www.sacurrent.com/feed/",
    "mediaType": "article",
    "itemSource": "San Antonio Current",
    "counties": [
      "texas/pecos",
      "texas/goliad",
      "texas/bee"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Current (2)",
    "url": "https://sacurrent.com/feed/",
    "mediaType": "article",
    "itemSource": "San Antonio Current",
    "counties": [
      "texas/pecos",
      "texas/goliad",
      "texas/bee"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Report",
    "url": "https://sanantonioreport.org/feed/",
    "mediaType": "article",
    "itemSource": "San Antonio Report",
    "counties": [
      "texas/bexar"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Report (2)",
    "url": "https://sanantonioreport.org/rss",
    "mediaType": "article",
    "itemSource": "San Antonio Report",
    "counties": [
      "texas/bexar"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Securities Io",
    "url": "https://www.securities.io/feed/",
    "mediaType": "article",
    "itemSource": "Securities Io",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Securities Io (2)",
    "url": "https://securities.io/feed/",
    "mediaType": "article",
    "itemSource": "Securities Io",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Seguin Today",
    "url": "https://seguintoday.com/feed/",
    "mediaType": "article",
    "itemSource": "Seguin Today",
    "counties": [
      "texas/guadalupe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Seguin Today (2)",
    "url": "https://seguintoday.com/rss",
    "mediaType": "article",
    "itemSource": "Seguin Today",
    "counties": [
      "texas/guadalupe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Snopes",
    "url": "https://snopes.com/feed/",
    "mediaType": "article",
    "itemSource": "Snopes",
    "counties": [
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Snopes (2)",
    "url": "https://snopes.com/news/feed/",
    "mediaType": "article",
    "itemSource": "Snopes",
    "counties": [
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texas Monthly",
    "url": "https://texasmonthly.com/feed/",
    "mediaType": "article",
    "itemSource": "Texas Monthly",
    "counties": [
      "texas/panola",
      "texas/hemphill",
      "texas/bee"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texas Monthly (2)",
    "url": "https://texasmonthly.com/rss",
    "mediaType": "article",
    "itemSource": "Texas Monthly",
    "counties": [
      "texas/panola",
      "texas/hemphill",
      "texas/bee"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texoma's Homepage",
    "url": "https://www.texomashomepage.com/feed/",
    "mediaType": "article",
    "itemSource": "Texoma's Homepage",
    "counties": [
      "texas/archer",
      "texas/wichita"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texoma's Homepage (2)",
    "url": "https://www.texomashomepage.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "Texoma's Homepage",
    "counties": [
      "texas/archer",
      "texas/wichita"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Atlantic",
    "url": "https://theatlantic.com/feed/all/",
    "mediaType": "article",
    "itemSource": "The Atlantic",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Atlantic (2)",
    "url": "https://theatlantic.com/feed/best-of/",
    "mediaType": "article",
    "itemSource": "The Atlantic",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Daily Beast",
    "url": "https://thedailybeast.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "The Daily Beast",
    "counties": [
      "texas/delta",
      "texas/llano"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Daily News",
    "url": "http://www.galvnews.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "The Daily News",
    "counties": [
      "texas/galveston"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Gilmer Mirror",
    "url": "https://www.gilmermirror.com/feed/",
    "mediaType": "article",
    "itemSource": "The Gilmer Mirror",
    "counties": [
      "texas/upshur"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Gilmer Mirror (2)",
    "url": "https://www.gilmermirror.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "The Gilmer Mirror",
    "counties": [
      "texas/upshur"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Guardian",
    "url": "https://theguardian.com/rss",
    "mediaType": "article",
    "itemSource": "The Guardian",
    "counties": [
      "texas/menard",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Herald-Banner",
    "url": "http://www.heraldbanner.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "The Herald-Banner",
    "counties": [
      "texas/hunt"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Huntsville Item",
    "url": "http://www.itemonline.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "The Huntsville Item",
    "counties": [
      "texas/walker"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Korea Times",
    "url": "https://feed.koreatimes.co.kr/k/allnews.xml",
    "mediaType": "article",
    "itemSource": "The Korea Times",
    "counties": [
      "texas/wharton"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The New Yorker",
    "url": "https://www.newyorker.com/feed/rss",
    "mediaType": "article",
    "itemSource": "The New Yorker",
    "counties": [
      "texas/loving",
      "texas/hays"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Paris News",
    "url": "http://theparisnews.com/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "The Paris News",
    "counties": [
      "texas/lamar"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Texan",
    "url": "http://thetexan.news/search/?f=rss&t=article&l=50&s=start_time&sd=desc&k%5B%5D=%23topstory",
    "mediaType": "article",
    "itemSource": "The Texan",
    "counties": [
      "texas/galveston"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The University Star",
    "url": "https://universitystar.com/feed/",
    "mediaType": "article",
    "itemSource": "The University Star",
    "counties": [
      "texas/hays"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The University Star (2)",
    "url": "https://universitystar.com/feed/atom/",
    "mediaType": "article",
    "itemSource": "The University Star",
    "counties": [
      "texas/hays"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Toronto Sun",
    "url": "https://torontosun.com/feed/",
    "mediaType": "article",
    "itemSource": "Toronto Sun",
    "counties": [
      "texas/hemphill",
      "texas/angelina"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Toronto Sun (2)",
    "url": "https://torontosun.com/rss",
    "mediaType": "article",
    "itemSource": "Toronto Sun",
    "counties": [
      "texas/hemphill",
      "texas/angelina"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Tyler Morning Telegraph",
    "url": "https://tylerpaper.com/feed/",
    "mediaType": "article",
    "itemSource": "Tyler Morning Telegraph",
    "counties": [
      "texas/upshur",
      "texas/marion",
      "texas/rusk",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Tyler Morning Telegraph (2)",
    "url": "https://tylerpaper.com/rss",
    "mediaType": "article",
    "itemSource": "Tyler Morning Telegraph",
    "counties": [
      "texas/upshur",
      "texas/marion",
      "texas/rusk",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "UPI",
    "url": "https://rss.upi.com/news/news.rss",
    "mediaType": "article",
    "itemSource": "UPI",
    "counties": [
      "texas/real"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Us Weekly",
    "url": "https://usmagazine.com/feed/",
    "mediaType": "article",
    "itemSource": "Us Weekly",
    "counties": [
      "texas/carson",
      "texas/henderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Us Weekly (2)",
    "url": "https://usmagazine.com/rss",
    "mediaType": "article",
    "itemSource": "Us Weekly",
    "counties": [
      "texas/carson",
      "texas/henderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WBAP",
    "url": "https://wbap.com/feed/",
    "mediaType": "article",
    "itemSource": "WBAP",
    "counties": [
      "texas/palo-pinto"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WBAP (2)",
    "url": "https://wbap.com/rss",
    "mediaType": "article",
    "itemSource": "WBAP",
    "counties": [
      "texas/palo-pinto"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WFAA8",
    "url": "https://www.wfaa.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "WFAA8",
    "counties": [
      "texas/parker",
      "texas/cooke",
      "texas/dallas",
      "texas/montague",
      "texas/van-zandt",
      "texas/ellis",
      "texas/delta",
      "texas/somervell",
      "texas/cherokee",
      "texas/denton",
      "texas/johnson",
      "texas/wilbarger",
      "texas/fannin",
      "texas/hunt",
      "texas/nacogdoches",
      "texas/rains",
      "texas/henderson",
      "texas/rockwall",
      "texas/erath",
      "texas/freestone",
      "texas/grayson",
      "texas/hopkins",
      "texas/kaufman",
      "texas/wise",
      "texas/archer",
      "texas/navarro",
      "texas/tarrant",
      "texas/eastland",
      "texas/jack"
    ],
    "trustedForCountyTier": false
  }
];
