// Generated by: npm run discover:sources && npm run probe:sources && npm run emit:sources
// Do not edit by hand. Outlets promoted to trusted belong in the reviewed
// countyNativeSources list in source-registry.ts.
//
// Local and regional outlets observed writing about specific counties, each
// with a feed that parses and carries recent items. Their feeds are fetched
// for the counties listed, which is the point — it is where the additional
// county coverage comes from — but trustedForCountyTier is false throughout,
// so every story still has to name the county or one of its towns. Without
// that, one regional newsroom would fill twenty county desks with the same
// regional wire.
import type { CountyNativeSource, DirectSource } from "./source-registry.js";

// Reserved for outlets promoted after review; discovery never fills this.
export const discoveredCountyNativeSources: CountyNativeSource[] = [];

export const discoveredRegionalSources: DirectSource[] = [
  {
    "name": "101.5 KNUE Country Radio",
    "url": "https://knue.com/feed/",
    "mediaType": "article",
    "itemSource": "101.5 KNUE Country Radio",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "101.5 KNUE Country Radio (2)",
    "url": "https://knue.com/rss",
    "mediaType": "article",
    "itemSource": "101.5 KNUE Country Radio",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "12 NEWS",
    "url": "https://www.12newsnow.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "12 NEWS",
    "counties": [
      "texas/orange",
      "texas/newton",
      "texas/hardin",
      "texas/jefferson",
      "texas/tyler",
      "texas/jasper",
      "texas/palo-pinto",
      "texas/blanco",
      "texas/brooks",
      "texas/sabine"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "12 NEWS (2)",
    "url": "https://12newsnow.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "12 NEWS",
    "counties": [
      "texas/orange",
      "texas/newton",
      "texas/hardin",
      "texas/jefferson",
      "texas/tyler",
      "texas/jasper",
      "texas/palo-pinto",
      "texas/blanco",
      "texas/brooks",
      "texas/sabine"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "13abc",
    "url": "https://13abc.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "13abc",
    "counties": [
      "texas/victoria"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "25 News KXXV",
    "url": "https://www.kxxv.com/index.rss",
    "mediaType": "article",
    "itemSource": "25 News KXXV",
    "counties": [
      "texas/hamilton"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ABC13 Houston",
    "url": "https://abc13.com/feed/",
    "mediaType": "article",
    "itemSource": "ABC13 Houston",
    "counties": [
      "texas/matagorda",
      "texas/fort-bend",
      "texas/san-jacinto",
      "texas/henderson",
      "texas/houston",
      "texas/liberty",
      "texas/waller",
      "texas/gregg",
      "texas/harris",
      "texas/brazoria",
      "texas/chambers",
      "texas/jackson",
      "texas/leon",
      "texas/tarrant",
      "texas/walker",
      "texas/kinney",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ABC13 Houston (2)",
    "url": "https://abc13.com/rss",
    "mediaType": "article",
    "itemSource": "ABC13 Houston",
    "counties": [
      "texas/matagorda",
      "texas/fort-bend",
      "texas/san-jacinto",
      "texas/henderson",
      "texas/houston",
      "texas/liberty",
      "texas/waller",
      "texas/gregg",
      "texas/harris",
      "texas/brazoria",
      "texas/chambers",
      "texas/jackson",
      "texas/leon",
      "texas/tarrant",
      "texas/walker",
      "texas/kinney",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "AgriLife Today",
    "url": "https://agrilifetoday.tamu.edu/feed/",
    "mediaType": "article",
    "itemSource": "AgriLife Today",
    "counties": [
      "texas/mason",
      "texas/brazos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "AgriLife Today (2)",
    "url": "https://agrilifetoday.tamu.edu/rss",
    "mediaType": "article",
    "itemSource": "AgriLife Today",
    "counties": [
      "texas/mason",
      "texas/brazos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Cbs19",
    "url": "https://www.cbs19.tv/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Cbs19",
    "counties": [
      "texas/wood",
      "texas/harrison",
      "texas/angelina"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Cbs19 (2)",
    "url": "https://cbs19.tv/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Cbs19",
    "counties": [
      "texas/wood",
      "texas/harrison",
      "texas/angelina"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Click2Houston",
    "url": "https://click2houston.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "Click2Houston",
    "counties": [
      "texas/polk",
      "texas/brazoria",
      "texas/austin",
      "texas/galveston",
      "texas/ector",
      "texas/grimes",
      "texas/houston",
      "texas/liberty",
      "texas/mclennan",
      "texas/uvalde",
      "texas/fort-bend",
      "texas/harris",
      "texas/hood",
      "texas/san-jacinto"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Colorado Politics",
    "url": "https://www.coloradopolitics.com/feed/",
    "mediaType": "article",
    "itemSource": "Colorado Politics",
    "counties": [
      "texas/el-paso"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Colorado Politics (2)",
    "url": "https://coloradopolitics.com/feed/",
    "mediaType": "article",
    "itemSource": "Colorado Politics",
    "counties": [
      "texas/el-paso"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Community Impact",
    "url": "https://communityimpact.com/rss/",
    "mediaType": "article",
    "itemSource": "Community Impact",
    "counties": [
      "texas/collin",
      "texas/williamson",
      "texas/brazos",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Community Impact (2)",
    "url": "https://communityimpact.com/rss",
    "mediaType": "article",
    "itemSource": "Community Impact",
    "counties": [
      "texas/collin",
      "texas/williamson",
      "texas/brazos",
      "texas/montgomery"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Conchovalleyhomepage",
    "url": "https://conchovalleyhomepage.com/feed/",
    "mediaType": "article",
    "itemSource": "Conchovalleyhomepage",
    "counties": [
      "texas/tom-green"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Conchovalleyhomepage (2)",
    "url": "https://conchovalleyhomepage.com/rss",
    "mediaType": "article",
    "itemSource": "Conchovalleyhomepage",
    "counties": [
      "texas/tom-green"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Crooks and Liars",
    "url": "https://crooksandliars.com/feeds/latest",
    "mediaType": "article",
    "itemSource": "Crooks and Liars",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Crooks and Liars (2)",
    "url": "http://feeds.crooksandliars.com/crooksandliars/YaCP",
    "mediaType": "article",
    "itemSource": "Crooks and Liars",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "CW39 Houston",
    "url": "https://cw39.com/feed/",
    "mediaType": "article",
    "itemSource": "CW39 Houston",
    "counties": [
      "texas/hardin",
      "texas/jack"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "CW39 Houston (2)",
    "url": "https://cw39.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "CW39 Houston",
    "counties": [
      "texas/hardin",
      "texas/jack"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Everythinglubbock",
    "url": "https://everythinglubbock.com/feed/",
    "mediaType": "article",
    "itemSource": "Everythinglubbock",
    "counties": [
      "texas/gaines",
      "texas/cochran"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Everythinglubbock (2)",
    "url": "https://everythinglubbock.com/rss",
    "mediaType": "article",
    "itemSource": "Everythinglubbock",
    "counties": [
      "texas/gaines",
      "texas/cochran"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 4 News Dallas-Fort Worth",
    "url": "https://www.fox4news.com/rss.xml",
    "mediaType": "article",
    "itemSource": "FOX 4 News Dallas-Fort Worth",
    "counties": [
      "texas/travis",
      "texas/van-zandt"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 4 News Dallas-Fort Worth (2)",
    "url": "https://www.fox4news.com/rss/category/news",
    "mediaType": "article",
    "itemSource": "FOX 4 News Dallas-Fort Worth",
    "counties": [
      "texas/travis",
      "texas/van-zandt"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 7 Austin",
    "url": "https://www.fox7austin.com/rss.xml",
    "mediaType": "article",
    "itemSource": "FOX 7 Austin",
    "counties": [
      "texas/travis",
      "texas/uvalde"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX 7 Austin (2)",
    "url": "https://www.fox7austin.com/rss/category/news",
    "mediaType": "article",
    "itemSource": "FOX 7 Austin",
    "counties": [
      "texas/travis",
      "texas/uvalde"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Fox Business Network",
    "url": "https://moxie.foxbusiness.com/google-publisher/latest.xml",
    "mediaType": "article",
    "itemSource": "Fox Business Network",
    "counties": [
      "texas/armstrong",
      "texas/cameron"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Fox Business Network (2)",
    "url": "https://foxbusiness.com/rss.xml",
    "mediaType": "article",
    "itemSource": "Fox Business Network",
    "counties": [
      "texas/armstrong",
      "texas/cameron"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX21 News Colorado",
    "url": "https://fox21news.com/feed/",
    "mediaType": "article",
    "itemSource": "FOX21 News Colorado",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX21 News Colorado (2)",
    "url": "https://fox21news.com/rss",
    "mediaType": "article",
    "itemSource": "FOX21 News Colorado",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX59 News",
    "url": "https://fox59.com/feed/",
    "mediaType": "article",
    "itemSource": "FOX59 News",
    "counties": [
      "texas/loving"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "FOX59 News (2)",
    "url": "https://fox59.com/rss",
    "mediaType": "article",
    "itemSource": "FOX59 News",
    "counties": [
      "texas/loving"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Government Technology",
    "url": "https://www.govtech.com/index.rss",
    "mediaType": "article",
    "itemSource": "Government Technology",
    "counties": [
      "texas/bosque",
      "texas/coryell",
      "texas/bastrop",
      "texas/harris",
      "texas/johnson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Grist",
    "url": "https://grist.org/feed/",
    "mediaType": "article",
    "itemSource": "Grist",
    "counties": [
      "texas/crockett",
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Grist (2)",
    "url": "https://grist.org/rss",
    "mediaType": "article",
    "itemSource": "Grist",
    "counties": [
      "texas/crockett",
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Hoodline",
    "url": "https://hoodline.com/rss.xml",
    "mediaType": "article",
    "itemSource": "Hoodline",
    "counties": [
      "texas/kendall"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "HousingWire",
    "url": "https://www.housingwire.com/feed/",
    "mediaType": "article",
    "itemSource": "HousingWire",
    "counties": [
      "texas/collin",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "HousingWire (2)",
    "url": "https://www.housingwire.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "HousingWire",
    "counties": [
      "texas/collin",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Houston Public Media",
    "url": "https://www.houstonpublicmedia.org/rsslatest.xml",
    "mediaType": "article",
    "itemSource": "Houston Public Media",
    "counties": [
      "texas/polk",
      "texas/galveston",
      "texas/houston",
      "texas/montgomery",
      "texas/waller",
      "texas/brazoria",
      "texas/harris"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Houston Public Media (2)",
    "url": "https://houstonpublicmedia.org/feed/",
    "mediaType": "article",
    "itemSource": "Houston Public Media",
    "counties": [
      "texas/polk",
      "texas/galveston",
      "texas/houston",
      "texas/montgomery",
      "texas/waller",
      "texas/brazoria",
      "texas/harris"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Independent Journal Review",
    "url": "https://ijr.com/feed/",
    "mediaType": "article",
    "itemSource": "Independent Journal Review",
    "counties": [
      "texas/milam",
      "texas/harris"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Independent Journal Review (2)",
    "url": "https://ijr.com/feed.xml",
    "mediaType": "article",
    "itemSource": "Independent Journal Review",
    "counties": [
      "texas/milam",
      "texas/harris"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "InForum",
    "url": "https://www.inforum.com/index.rss",
    "mediaType": "article",
    "itemSource": "InForum",
    "counties": [
      "texas/kleberg"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "InsideClimate News",
    "url": "https://insideclimatenews.org/feed/",
    "mediaType": "article",
    "itemSource": "InsideClimate News",
    "counties": [
      "texas/somervell",
      "texas/pecos",
      "texas/jim-wells",
      "texas/caldwell",
      "texas/tom-green",
      "texas/webb",
      "texas/winkler",
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Insurance Journal",
    "url": "https://insurancejournal.com/feed/",
    "mediaType": "article",
    "itemSource": "Insurance Journal",
    "counties": [
      "texas/gregg",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Insurance Journal (2)",
    "url": "https://insurancejournal.com/rss",
    "mediaType": "article",
    "itemSource": "Insurance Journal",
    "counties": [
      "texas/gregg",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KARE",
    "url": "https://www.kare11.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KARE",
    "counties": [
      "texas/washington"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KARE (2)",
    "url": "https://kare11.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KARE",
    "counties": [
      "texas/washington"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KBTX",
    "url": "https://kbtx.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KBTX",
    "counties": [
      "texas/leon",
      "texas/walker",
      "texas/burleson",
      "texas/hood",
      "texas/palo-pinto",
      "texas/erath",
      "texas/fayette",
      "texas/grimes",
      "texas/lee",
      "texas/milam",
      "texas/robertson",
      "texas/madison"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KCBD",
    "url": "https://kcbd.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KCBD",
    "counties": [
      "texas/hale",
      "texas/lubbock",
      "texas/williamson",
      "texas/garza"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KCEN-TV",
    "url": "https://www.kcentv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KCEN-TV",
    "counties": [
      "texas/hamilton",
      "texas/bell",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KCEN-TV (2)",
    "url": "https://kcentv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KCEN-TV",
    "counties": [
      "texas/hamilton",
      "texas/bell",
      "texas/lampasas"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Ketk",
    "url": "https://ketk.com/feed/",
    "mediaType": "article",
    "itemSource": "Ketk",
    "counties": [
      "texas/trinity",
      "texas/smith",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Ketk (2)",
    "url": "https://ketk.com/rss",
    "mediaType": "article",
    "itemSource": "Ketk",
    "counties": [
      "texas/trinity",
      "texas/smith",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KHOU",
    "url": "https://www.khou.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KHOU",
    "counties": [
      "texas/galveston",
      "texas/waller",
      "texas/kendall",
      "texas/val-verde",
      "texas/harris",
      "texas/brazoria",
      "texas/chambers",
      "texas/childress",
      "texas/nacogdoches",
      "texas/houston",
      "texas/kerr",
      "texas/uvalde",
      "texas/victoria",
      "texas/wharton",
      "texas/bell",
      "texas/ector",
      "texas/fort-bend",
      "texas/liberty",
      "texas/montgomery",
      "texas/polk",
      "texas/zavala",
      "texas/grimes",
      "texas/rockwall",
      "texas/travis",
      "texas/wise",
      "texas/san-jacinto",
      "texas/tyler"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KHOU (2)",
    "url": "https://khou.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KHOU",
    "counties": [
      "texas/galveston",
      "texas/waller",
      "texas/kendall",
      "texas/val-verde",
      "texas/harris",
      "texas/brazoria",
      "texas/chambers",
      "texas/childress",
      "texas/nacogdoches",
      "texas/houston",
      "texas/kerr",
      "texas/uvalde",
      "texas/victoria",
      "texas/wharton",
      "texas/bell",
      "texas/ector",
      "texas/fort-bend",
      "texas/liberty",
      "texas/montgomery",
      "texas/polk",
      "texas/zavala",
      "texas/grimes",
      "texas/rockwall",
      "texas/travis",
      "texas/wise",
      "texas/san-jacinto",
      "texas/tyler"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Kiii3 News",
    "url": "https://www.kiiitv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Kiii3 News",
    "counties": [
      "texas/bee",
      "texas/kleberg",
      "texas/mcmullen",
      "texas/goliad",
      "texas/aransas",
      "texas/brooks",
      "texas/jim-hogg",
      "texas/live-oak",
      "texas/nueces",
      "texas/burleson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Kiii3 News (2)",
    "url": "https://kiiitv.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "Kiii3 News",
    "counties": [
      "texas/bee",
      "texas/kleberg",
      "texas/mcmullen",
      "texas/goliad",
      "texas/aransas",
      "texas/brooks",
      "texas/jim-hogg",
      "texas/live-oak",
      "texas/nueces",
      "texas/burleson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KLTV",
    "url": "https://kltv.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KLTV",
    "counties": [
      "texas/henderson",
      "texas/upshur",
      "texas/angelina",
      "texas/rusk",
      "texas/smith",
      "texas/houston",
      "texas/rains",
      "texas/wood",
      "texas/cherokee",
      "texas/gregg",
      "texas/anderson",
      "texas/harrison",
      "texas/hopkins",
      "texas/marion",
      "texas/franklin",
      "texas/newton",
      "texas/van-zandt"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Kristv",
    "url": "https://www.kristv.com/index.rss",
    "mediaType": "article",
    "itemSource": "Kristv",
    "counties": [
      "texas/refugio",
      "texas/nueces",
      "texas/bee",
      "texas/kleberg",
      "texas/aransas",
      "texas/kenedy",
      "texas/live-oak",
      "texas/jim-wells",
      "texas/san-patricio"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KSAT",
    "url": "https://ksat.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KSAT",
    "counties": [
      "texas/bandera",
      "texas/frio",
      "texas/maverick",
      "texas/uvalde",
      "texas/atascosa",
      "texas/guadalupe",
      "texas/wilson",
      "texas/comal",
      "texas/kendall",
      "texas/edwards",
      "texas/goliad",
      "texas/zavala",
      "texas/blanco",
      "texas/medina",
      "texas/live-oak",
      "texas/fayette",
      "texas/karnes",
      "texas/la-salle",
      "texas/lavaca",
      "texas/gillespie",
      "texas/kinney",
      "texas/starr",
      "texas/val-verde",
      "texas/bee",
      "texas/bexar",
      "texas/howard",
      "texas/aransas",
      "texas/brazoria",
      "texas/brooks",
      "texas/foard",
      "texas/hunt"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KSLA",
    "url": "https://ksla.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KSLA",
    "counties": [
      "texas/harrison",
      "texas/marion",
      "texas/bowie",
      "texas/cass"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KTRE",
    "url": "https://ktre.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KTRE",
    "counties": [
      "texas/tyler",
      "texas/nacogdoches",
      "texas/houston",
      "texas/angelina",
      "texas/shelby",
      "texas/trinity",
      "texas/polk"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVIA",
    "url": "https://kvia.com/feed/",
    "mediaType": "article",
    "itemSource": "KVIA",
    "counties": [
      "texas/culberson",
      "texas/hudspeth",
      "texas/zavala"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVIA (2)",
    "url": "https://kvia.com/rss",
    "mediaType": "article",
    "itemSource": "KVIA",
    "counties": [
      "texas/culberson",
      "texas/hudspeth",
      "texas/zavala"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVUE",
    "url": "https://www.kvue.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KVUE",
    "counties": [
      "texas/mason",
      "texas/williamson",
      "texas/bastrop",
      "texas/caldwell",
      "texas/fayette",
      "texas/burnet",
      "texas/wilbarger",
      "texas/jim-hogg",
      "texas/lee",
      "texas/milam",
      "texas/bee",
      "texas/gillespie",
      "texas/blanco",
      "texas/brazoria",
      "texas/hays",
      "texas/henderson",
      "texas/orange",
      "texas/palo-pinto",
      "texas/comal",
      "texas/hill",
      "texas/llano",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KVUE (2)",
    "url": "https://kvue.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "KVUE",
    "counties": [
      "texas/mason",
      "texas/williamson",
      "texas/bastrop",
      "texas/caldwell",
      "texas/fayette",
      "texas/burnet",
      "texas/wilbarger",
      "texas/jim-hogg",
      "texas/lee",
      "texas/milam",
      "texas/bee",
      "texas/gillespie",
      "texas/blanco",
      "texas/brazoria",
      "texas/hays",
      "texas/henderson",
      "texas/orange",
      "texas/palo-pinto",
      "texas/comal",
      "texas/hill",
      "texas/llano",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KWTX",
    "url": "https://kwtx.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "KWTX",
    "counties": [
      "texas/hill",
      "texas/hamilton",
      "texas/coryell",
      "texas/mclennan",
      "texas/angelina",
      "texas/milam",
      "texas/bosque",
      "texas/leon",
      "texas/limestone",
      "texas/falls",
      "texas/guadalupe",
      "texas/lampasas",
      "texas/childress",
      "texas/erath",
      "texas/freestone",
      "texas/tom-green",
      "texas/williamson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KXAN Austin",
    "url": "https://www.kxan.com/feed/",
    "mediaType": "article",
    "itemSource": "KXAN Austin",
    "counties": [
      "texas/blanco",
      "texas/caldwell",
      "texas/mason",
      "texas/williamson",
      "texas/gregg",
      "texas/bastrop",
      "texas/gillespie",
      "texas/starr",
      "texas/fayette",
      "texas/midland",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "KXAN Austin (2)",
    "url": "https://www.kxan.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "KXAN Austin",
    "counties": [
      "texas/blanco",
      "texas/caldwell",
      "texas/mason",
      "texas/williamson",
      "texas/gregg",
      "texas/bastrop",
      "texas/gillespie",
      "texas/starr",
      "texas/fayette",
      "texas/midland",
      "texas/travis"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Law",
    "url": "https://law.com/news/feed/",
    "mediaType": "article",
    "itemSource": "Law",
    "counties": [
      "texas/midland",
      "texas/guadalupe",
      "texas/brown"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Longview News-Journal",
    "url": "https://news-journal.com/feed/",
    "mediaType": "article",
    "itemSource": "Longview News-Journal",
    "counties": [
      "texas/franklin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Longview News-Journal (2)",
    "url": "https://news-journal.com/rss",
    "mediaType": "article",
    "itemSource": "Longview News-Journal",
    "counties": [
      "texas/franklin"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "MPR News",
    "url": "https://www.mprnews.org/feed/homepage",
    "mediaType": "article",
    "itemSource": "MPR News",
    "counties": [
      "texas/washington"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ms",
    "url": "https://www.ms.now/feed",
    "mediaType": "article",
    "itemSource": "ms",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ms (2)",
    "url": "https://ms.now/feed/",
    "mediaType": "article",
    "itemSource": "ms",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "MyHighPlains",
    "url": "https://myhighplains.com/feed/",
    "mediaType": "article",
    "itemSource": "MyHighPlains",
    "counties": [
      "texas/randall"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "MyHighPlains (2)",
    "url": "https://myhighplains.com/rss",
    "mediaType": "article",
    "itemSource": "MyHighPlains",
    "counties": [
      "texas/randall"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NBC DFW",
    "url": "https://www.nbcdfw.com/?rss=y",
    "mediaType": "article",
    "itemSource": "NBC DFW",
    "counties": [
      "texas/crockett",
      "texas/kaufman",
      "texas/denton",
      "texas/fannin",
      "texas/collin",
      "texas/cooke",
      "texas/dallas",
      "texas/hunt",
      "texas/johnson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NBC DFW (2)",
    "url": "https://nbcdfw.com/feed/",
    "mediaType": "article",
    "itemSource": "NBC DFW",
    "counties": [
      "texas/crockett",
      "texas/kaufman",
      "texas/denton",
      "texas/fannin",
      "texas/collin",
      "texas/cooke",
      "texas/dallas",
      "texas/hunt",
      "texas/johnson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "New York Post",
    "url": "https://nypost.com/feed/",
    "mediaType": "article",
    "itemSource": "New York Post",
    "counties": [
      "texas/maverick",
      "texas/parker",
      "texas/webb",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "New York Post (2)",
    "url": "https://nypost.com/rss",
    "mediaType": "article",
    "itemSource": "New York Post",
    "counties": [
      "texas/maverick",
      "texas/parker",
      "texas/webb",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "News Channel 6",
    "url": "https://newschannel6now.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "News Channel 6",
    "counties": [
      "texas/jack"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NewsChannel 10",
    "url": "https://newschannel10.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "NewsChannel 10",
    "counties": [
      "texas/deaf-smith",
      "texas/wheeler",
      "texas/hutchinson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NewsWest 9",
    "url": "https://www.newswest9.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "NewsWest 9",
    "counties": [
      "texas/presidio",
      "texas/crane",
      "texas/howard",
      "texas/ector",
      "texas/midland",
      "texas/andrews",
      "texas/pecos",
      "texas/scurry",
      "texas/brewster",
      "texas/reeves",
      "texas/martin",
      "texas/terrell",
      "texas/ward"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "NewsWest 9 (2)",
    "url": "https://newswest9.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "NewsWest 9",
    "counties": [
      "texas/presidio",
      "texas/crane",
      "texas/howard",
      "texas/ector",
      "texas/midland",
      "texas/andrews",
      "texas/pecos",
      "texas/scurry",
      "texas/brewster",
      "texas/reeves",
      "texas/martin",
      "texas/terrell",
      "texas/ward"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "PolitiFact",
    "url": "https://politifact.com/feed/",
    "mediaType": "article",
    "itemSource": "PolitiFact",
    "counties": [
      "texas/gaines"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "PolitiFact (2)",
    "url": "https://politifact.com/rss",
    "mediaType": "article",
    "itemSource": "PolitiFact",
    "counties": [
      "texas/gaines"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "POWER Magazine",
    "url": "https://powermag.com/feed/",
    "mediaType": "article",
    "itemSource": "POWER Magazine",
    "counties": [
      "texas/milam",
      "texas/haskell",
      "texas/calhoun",
      "texas/runnels",
      "texas/somervell"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "POWER Magazine (2)",
    "url": "https://powermag.com/rss",
    "mediaType": "article",
    "itemSource": "POWER Magazine",
    "counties": [
      "texas/milam",
      "texas/haskell",
      "texas/calhoun",
      "texas/runnels",
      "texas/somervell"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ProPublica",
    "url": "https://www.propublica.org/feeds/propublica/main",
    "mediaType": "article",
    "itemSource": "ProPublica",
    "counties": [
      "texas/goliad",
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "ProPublica (2)",
    "url": "https://propublica.org/feed/",
    "mediaType": "article",
    "itemSource": "ProPublica",
    "counties": [
      "texas/goliad",
      "texas/kerr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "REBusinessOnline",
    "url": "https://rebusinessonline.com/feed/",
    "mediaType": "article",
    "itemSource": "REBusinessOnline",
    "counties": [
      "texas/briscoe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "REBusinessOnline (2)",
    "url": "https://rebusinessonline.com/rss",
    "mediaType": "article",
    "itemSource": "REBusinessOnline",
    "counties": [
      "texas/briscoe"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Religion News Service",
    "url": "https://religionnews.com/feed/",
    "mediaType": "article",
    "itemSource": "Religion News Service",
    "counties": [
      "texas/hood",
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Religion News Service (2)",
    "url": "https://religionnews.com/?feed=rss2",
    "mediaType": "article",
    "itemSource": "Religion News Service",
    "counties": [
      "texas/hood",
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Current",
    "url": "https://www.sacurrent.com/feed/",
    "mediaType": "article",
    "itemSource": "San Antonio Current",
    "counties": [
      "texas/goliad",
      "texas/bee",
      "texas/pecos",
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "San Antonio Current (2)",
    "url": "https://sacurrent.com/feed/",
    "mediaType": "article",
    "itemSource": "San Antonio Current",
    "counties": [
      "texas/goliad",
      "texas/bee",
      "texas/pecos",
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Securities Io",
    "url": "https://www.securities.io/feed/",
    "mediaType": "article",
    "itemSource": "Securities Io",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Securities Io (2)",
    "url": "https://securities.io/feed/",
    "mediaType": "article",
    "itemSource": "Securities Io",
    "counties": [
      "texas/milam"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "SignalSCV",
    "url": "https://signalscv.com/feed/",
    "mediaType": "article",
    "itemSource": "SignalSCV",
    "counties": [
      "texas/williamson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "SignalSCV (2)",
    "url": "https://signalscv.com/rss",
    "mediaType": "article",
    "itemSource": "SignalSCV",
    "counties": [
      "texas/williamson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texas Monthly",
    "url": "https://texasmonthly.com/feed/",
    "mediaType": "article",
    "itemSource": "Texas Monthly",
    "counties": [
      "texas/crane",
      "texas/hemphill",
      "texas/panola",
      "texas/brooks"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Texas Monthly (2)",
    "url": "https://texasmonthly.com/rss",
    "mediaType": "article",
    "itemSource": "Texas Monthly",
    "counties": [
      "texas/crane",
      "texas/hemphill",
      "texas/panola",
      "texas/brooks"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Atlantic",
    "url": "https://theatlantic.com/feed/all/",
    "mediaType": "article",
    "itemSource": "The Atlantic",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Atlantic (2)",
    "url": "https://theatlantic.com/feed/best-of/",
    "mediaType": "article",
    "itemSource": "The Atlantic",
    "counties": [
      "texas/starr"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Daily Beast",
    "url": "https://thedailybeast.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "The Daily Beast",
    "counties": [
      "texas/llano",
      "texas/delta",
      "texas/navarro"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Daily Signal",
    "url": "https://dailysignal.com/feed/",
    "mediaType": "article",
    "itemSource": "The Daily Signal",
    "counties": [
      "texas/henderson",
      "texas/hudspeth"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Globe and Mail",
    "url": "https://theglobeandmail.com/arc/outboundfeeds/rss/?outputType=xml",
    "mediaType": "article",
    "itemSource": "The Globe and Mail",
    "counties": [
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Guardian",
    "url": "https://theguardian.com/rss",
    "mediaType": "article",
    "itemSource": "The Guardian",
    "counties": [
      "texas/menard",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Guardian (2)",
    "url": "https://theguardian.com/news/rss",
    "mediaType": "article",
    "itemSource": "The Guardian",
    "counties": [
      "texas/menard",
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The New Yorker",
    "url": "https://www.newyorker.com/feed/rss",
    "mediaType": "article",
    "itemSource": "The New Yorker",
    "counties": [
      "texas/loving",
      "texas/presidio",
      "texas/hays"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Paisano",
    "url": "https://paisano-online.com/feed/",
    "mediaType": "article",
    "itemSource": "The Paisano",
    "counties": [
      "texas/bexar"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Paisano (2)",
    "url": "https://paisano-online.com/feed/atom/",
    "mediaType": "article",
    "itemSource": "The Paisano",
    "counties": [
      "texas/bexar"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Verge",
    "url": "https://theverge.com/rss/index.xml",
    "mediaType": "article",
    "itemSource": "The Verge",
    "counties": [
      "texas/pecos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "The Verge (2)",
    "url": "https://theverge.com/rss.xml",
    "mediaType": "article",
    "itemSource": "The Verge",
    "counties": [
      "texas/pecos"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Toronto Sun",
    "url": "https://torontosun.com/feed/",
    "mediaType": "article",
    "itemSource": "Toronto Sun",
    "counties": [
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Toronto Sun (2)",
    "url": "https://torontosun.com/rss",
    "mediaType": "article",
    "itemSource": "Toronto Sun",
    "counties": [
      "texas/hemphill"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Townhall",
    "url": "https://townhall.com/feed/",
    "mediaType": "article",
    "itemSource": "Townhall",
    "counties": [
      "texas/webb"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Townhall (2)",
    "url": "https://townhall.com/news/feed/",
    "mediaType": "article",
    "itemSource": "Townhall",
    "counties": [
      "texas/webb"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Truthout",
    "url": "https://truthout.org/feed/?withoutcomments=1",
    "mediaType": "article",
    "itemSource": "Truthout",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Truthout (2)",
    "url": "https://truthout.org/feed/",
    "mediaType": "article",
    "itemSource": "Truthout",
    "counties": [
      "texas/tarrant"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Tyler Morning Telegraph",
    "url": "https://tylerpaper.com/feed/",
    "mediaType": "article",
    "itemSource": "Tyler Morning Telegraph",
    "counties": [
      "texas/upshur",
      "texas/rusk",
      "texas/marion",
      "texas/anderson",
      "texas/gregg",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Tyler Morning Telegraph (2)",
    "url": "https://tylerpaper.com/rss",
    "mediaType": "article",
    "itemSource": "Tyler Morning Telegraph",
    "counties": [
      "texas/upshur",
      "texas/rusk",
      "texas/marion",
      "texas/anderson",
      "texas/gregg",
      "texas/wood"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "UPI",
    "url": "https://rss.upi.com/news/news.rss",
    "mediaType": "article",
    "itemSource": "UPI",
    "counties": [
      "texas/real"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Us Weekly",
    "url": "https://usmagazine.com/rss.xml",
    "mediaType": "article",
    "itemSource": "Us Weekly",
    "counties": [
      "texas/henderson",
      "texas/carson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Us Weekly (2)",
    "url": "https://usmagazine.com/news/rss",
    "mediaType": "article",
    "itemSource": "Us Weekly",
    "counties": [
      "texas/henderson",
      "texas/carson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Valleycentral",
    "url": "https://valleycentral.com/feed/",
    "mediaType": "article",
    "itemSource": "Valleycentral",
    "counties": [
      "texas/bexar",
      "texas/hidalgo"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Valleycentral (2)",
    "url": "https://valleycentral.com/rss",
    "mediaType": "article",
    "itemSource": "Valleycentral",
    "counties": [
      "texas/bexar",
      "texas/hidalgo"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WFAA8",
    "url": "https://www.wfaa.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "WFAA8",
    "counties": [
      "texas/parker",
      "texas/cooke",
      "texas/rockwall",
      "texas/henderson",
      "texas/montague",
      "texas/delta",
      "texas/denton",
      "texas/ellis",
      "texas/kaufman",
      "texas/wise",
      "texas/van-zandt",
      "texas/grayson",
      "texas/somervell",
      "texas/cherokee",
      "texas/dallas",
      "texas/erath",
      "texas/fannin",
      "texas/freestone",
      "texas/hopkins",
      "texas/johnson",
      "texas/nacogdoches",
      "texas/collin",
      "texas/wilbarger",
      "texas/navarro",
      "texas/rains",
      "texas/archer",
      "texas/hunt",
      "texas/jack",
      "texas/tom-green"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WFAA8 (2)",
    "url": "https://wfaa.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "WFAA8",
    "counties": [
      "texas/parker",
      "texas/cooke",
      "texas/rockwall",
      "texas/henderson",
      "texas/montague",
      "texas/delta",
      "texas/denton",
      "texas/ellis",
      "texas/kaufman",
      "texas/wise",
      "texas/van-zandt",
      "texas/grayson",
      "texas/somervell",
      "texas/cherokee",
      "texas/dallas",
      "texas/erath",
      "texas/fannin",
      "texas/freestone",
      "texas/hopkins",
      "texas/johnson",
      "texas/nacogdoches",
      "texas/collin",
      "texas/wilbarger",
      "texas/navarro",
      "texas/rains",
      "texas/archer",
      "texas/hunt",
      "texas/jack",
      "texas/tom-green"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WPMT",
    "url": "https://www.fox43.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "WPMT",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "WPMT (2)",
    "url": "https://fox43.com/feeds/syndication/rss/news",
    "mediaType": "article",
    "itemSource": "WPMT",
    "counties": [
      "texas/anderson"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Yourbasin | Big 2 - Fox 24",
    "url": "https://www.yourbasin.com/feed/",
    "mediaType": "article",
    "itemSource": "Yourbasin | Big 2 - Fox 24",
    "counties": [
      "texas/ector",
      "texas/reeves"
    ],
    "trustedForCountyTier": false
  },
  {
    "name": "Yourbasin | Big 2 - Fox 24 (2)",
    "url": "https://www.yourbasin.com/comments/feed/",
    "mediaType": "article",
    "itemSource": "Yourbasin | Big 2 - Fox 24",
    "counties": [
      "texas/ector",
      "texas/reeves"
    ],
    "trustedForCountyTier": false
  }
];
